OnlineShop/Controllers/AddressController.cs
namespace OnlineShop.Web.Controllers
{
	using System.Diagnostics;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

	using Application.Extensions;
	using Application.Services.Interfaces;
	using Application.ViewModels.Address;

	public class AddressController : Controller
    {
		private readonly IUserProfileService userProfileService;
		private readonly IAddressService addressService;

		public AddressController(IAddressService addressService, IUserProfileService userProfileService)
		{
			this.addressService = addressService;
			this.userProfileService = userProfileService;
		}

		[HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			var model = await this.addressService.GetAddressAsync(userProfileGuid);

		
			return View(model);
        }

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> AddAddress()
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}


			bool addressExists = await this.addressService.UserHasAddress(userProfileGuid);

			if (addressExists)
			{
				return RedirectToAction("Index");
			}

			return View();
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> AddAddress(AddAddressViewModel model)
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			if (!ModelState.IsValid)
			{
				foreach (var error in ModelState.Values.SelectMany(v => v.Errors))
				{
					Debug.WriteLine($"Error: {error.ErrorMessage}");
				}
				return View(model);
			}

			bool result = await this.addressService.AddAddressAsync(model, userProfileGuid);

			if (!result)
			{
				return View();
			}

			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> DeleteAddress()
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return RedirectToAction("Index", "Home");
			}

			var result = await this.addressService.DeleteAddressAsync(userProfileGuid);

			if (result)
			{
				return RedirectToAction("Index", "Address"); 
			}

			return RedirectToAction("Index", "Address");
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> EditAddress()
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			EditAddressViewModel formModel = await addressService
				.GetEditAddressAsync(userProfileGuid);

			return View(formModel);
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> EditAddress(EditAddressViewModel model)
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			if (!ModelState.IsValid)
			{
				return View(model);
			}

			bool result = await addressService.EditAddressAsync(model, userProfileGuid);

			if (!result)
			{
				return View();
			}

			return RedirectToAction(nameof(Index));
		}
	}
}

OnlineShop/Controllers/ProfileController.cs
namespace OnlineShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Application.Extensions;
    using Application.Services.Interfaces;
    using Application.ViewModels.Profile;

    public class ProfileController : Controller
    {
        private readonly IUserProfileService userProfileService;

        public ProfileController(IUserProfileService userProfileService)
        {
            this.userProfileService = userProfileService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

            if (userProfileGuid == Guid.Empty)
            {
                return View();
            }

            UserProfileViewModel userProfile = await userProfileService.GetUserProfileById(userProfileGuid);

            return View(userProfile);
        }
	}
}

OnlineShop/Controllers/PurchasesController.cs
namespace OnlineShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Application.Extensions;
    using Application.Services.Interfaces;

	public class PurchasesController : Controller
    {
        private readonly IPurchaseService purchaseService;
        private readonly IUserProfileService userProfileService;

        public PurchasesController(IPurchaseService purchaseService, IUserProfileService userProfileService)
        {
            this.purchaseService = purchaseService;
            this.userProfileService = userProfileService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

            if (userProfileGuid == Guid.Empty)
            {
                return View();
            }

            var purchases = await this.purchaseService.GetAllPurchasesAsync(userProfileGuid);

            return View(purchases);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CreatePurchase()
        {
            Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

            if (userProfileGuid == Guid.Empty)
            {
                return View();
            }

            var result = await this.purchaseService.CreatePurchase(userProfileGuid);

            if (result)
            {
                return View("ThankYou");
            }

            return View();
        }
    }
}

OnlineShop/Views/Address/AddAddress.cshtml
@using OnlineShop.Application.ViewModels.Address
@model AddAddressViewModel

@{
    ViewData["HideLayoutParts"] = true;
}

@section PageStyles{
    <link rel="stylesheet" href="~/css/Address/AddressForm.css" asp-append-version="true" />
}

@section PageScripts {
    <partial name="_ValidationScriptsPartial" />
}

<div class="address-form-container">
    <div class="address-input-container">
        <h1>Add Address</h1>
        <form asp-action="AddAddress" method="post" class="input-containter">
            @Html.AntiForgeryToken()
            
            <span asp-validation-for="Country" class="warning"></span>
            <textarea asp-for="Country" rows="1" placeholder="Enter Country" spellcheck="false"></textarea>

            <span asp-validation-for="City" class="warning"></span>
            <textarea asp-for="City" rows="1" placeholder="Enter City" spellcheck="false"></textarea>

            <span asp-validation-for="Street" class="warning"></span>
            <textarea asp-for="Street" rows="1" placeholder="Enter Street" spellcheck="false"></textarea>

            <span asp-validation-for="PhoneNumber" class="warning"></span>
            <textarea asp-for="PhoneNumber" rows="1" placeholder="Enter Phone Number" spellcheck="false"></textarea>

            <button class="submit" type="submit">Add</button>
        </form>
        <div class="btn-container">
            <a asp-action="Index">Cancel</a>
        </div>
    </div>
</div>

OnlineShop/Views/Address/EditAddress.cshtml
@using OnlineShop.Application.ViewModels.Address
@model EditAddressViewModel

@{
    ViewData["HideLayoutParts"] = true;
}

@section PageStyles {
    <link rel="stylesheet" href="~/css/Address/AddressForm.css" asp-append-version="true" />
}

@section PageScripts {
    <partial name="_ValidationScriptsPartial" />
}

<div class="address-form-container">
    <div class="address-input-container">
        <h1>Edit Address</h1>
        <form asp-action="EditAddress" method="post" class="input-containter">
            @Html.AntiForgeryToken()
            <input type="hidden" asp-for="Id" />

            <span asp-validation-for="Country" class="warning"></span>
            <textarea asp-for="Country" rows="1" placeholder="Enter Country" spellcheck="false"></textarea>

            <span asp-validation-for="City" class="warning"></span>
            <textarea asp-for="City" rows="1" placeholder="Enter City" spellcheck="false"></textarea>

            <span asp-validation-for="Street" class="warning"></span>
            <textarea asp-for="Street" rows="1" placeholder="Enter Street" spellcheck="false"></textarea>

            <span asp-validation-for="PhoneNumber" class="warning"></span>
            <textarea asp-for="PhoneNumber" rows="1" placeholder="Enter Phone Number" spellcheck="false"></textarea>

            <button class="submit" type="submit">Save</button>
        </form>
        <div class="btn-container">
            <a asp-action="Index">Cancel</a>
        </div>
    </div>
</div>

OnlineShop/Views/Address/Index.cshtml
@using OnlineShop.Application.ViewModels.Address
@model AddressViewModel

@section PageStyles {
    <link rel="stylesheet" href="~/css/UserProfile/UserProfile.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/UserProfile/Address.css" asp-append-version="true" />
}

<div class="user-profile-container">
    <div class="link-container">
        <a asp-controller="Profile" asp-action="Index" style="color: grey;">Profile</a>
        <a asp-controller="Purchases" asp-action="Index" style="color: grey;">Purchases</a>
        <a asp-controller="Address" asp-action="Index" style="color: black;">Address</a>
    </div>
    <div class="address-section-container">
        @if(@Model == null){
            <div class="add-address-btn-container">
                <a asp-controller="Address" asp-action="AddAddress">
                    <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" class="plus" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                        <g>
                            <path fill="none" d="M0 0h24v24H0z"></path>
                            <path d="M11 11V5h2v6h6v2h-6v6h-2v-6H5v-2z"></path>
                        </g>
                    </svg>New Address
                </a>
            </div>
        } 
        else 
        {
            <div class="profile-address-container">
                <div class="address-card">
                    <p class="name">@Model.FullName</p>
                    <p class="address">
                        <span>Address:</span> @Model.DeliveryAddress
                    </p>
                    <p class="phone">
                        <span>Phone: </span>@Model.PhoneNumber
                    </p>
                    <div class="address-btn-container">
                        <a asp-controller="Address" asp-action="EditAddress">Edit</a>
                        <form action="@Url.Action("DeleteAddress", "Address")" method="post">
                            <button type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        }
        
    </div>

</div>