OnlineShop/Controllers/ProfileController.cs
namespace OnlineShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Application.Extensions;
    using Application.Services.Interfaces;
    using Application.ViewModels.Profile;

    public class ProfileController : Controller
    {
        private readonly IUserProfileService userProfileService;

        public ProfileController(IUserProfileService userProfileService)
        {
            this.userProfileService = userProfileService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

            if (userProfileGuid == Guid.Empty)
            {
                return View();
            }

            UserProfileViewModel userProfile = await userProfileService.GetUserProfileById(userProfileGuid);

            return View(userProfile);
        }
	}
}

OnlineShop/Controllers/PurchaseController.cs
namespace OnlineShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using OnlineShop.Application.Extensions;
    using OnlineShop.Application.Services;
    using OnlineShop.Application.Services.Interfaces;

	public class PurchaseController : Controller
    {
        private readonly IPurchaseService purchaseService;
        private readonly IUserProfileService userProfileService;

        public PurchaseController(IPurchaseService purchaseService, IUserProfileService userProfileService)
        {
            this.purchaseService = purchaseService;
            this.userProfileService = userProfileService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

            if (userProfileGuid == Guid.Empty)
            {
                return View();
            }

            var purchases = await this.purchaseService.GetAllPurchasesAsync(userProfileGuid);

            return View(purchases);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CreatePurchase()
        {
            Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

            if (userProfileGuid == Guid.Empty)
            {
                return View();
            }

            var result = await this.purchaseService.CreatePurchase(userProfileGuid);

            if (result)
            {
                return View("ThankYou");
            }

            return View();
        }
    }
}

OnlineShop/Views/Purchase/Index.cshtml
@using OnlineShop.Application.ViewModels.Purchase;
@model IEnumerable<PurchaseViewModel>

@section PageStyles {
	<link rel="stylesheet" href="~/css/UserProfile/Purchases.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/UserProfile/UserProfile.css" asp-append-version="true" />
}

<div class="user-profile-container">
	<div class="link-container">
		<a asp-controller="Profile" asp-action="Index" style="color: grey;">Profile</a>
		<a asp-controller="Purchase" asp-action="Index" style="color: black;">Purchases</a>
		<a asp-controller="Address" asp-action="Index" style="color: grey;">Address</a>
	</div>

	<div class="purchases-container">
		@if (Model.Count() == 0)
		{
			<span class="no-purchases-msg">No Purchases</span>
		}
		else
		{
			int productItemIndex = 0;
			@foreach (var purchase in Model)
			{
				<div class="purchased-items-card @(productItemIndex == Model.Count()-1 ? "single-item-card" : "")">
					<span class="date">@purchase.DatePurchased</span>
					<img class="img" src="@purchase.ImgUrl" alt="Product Image">
					<span class="name">@purchase.Name</span>
					<span class="qty">@(purchase.QuantityBought)</span>
					<span class="price">$@(purchase.TotalPrice)</span>
				</div>

				productItemIndex++;
			}
		}
	</div>

</div>