OnlineShop/Controllers/CartController.cs
namespace OnlineShop.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Authorization;
    
    using Application.Services.Interfaces;
	using Application.Extensions;
	using Application.ViewModels.Cart;
	using OnlineShop.Application.ViewModels.Address;

	public class CartController : Controller
    {
		private readonly IAddressService addressService;
		private readonly ICartService cartService;
		private readonly IUserProfileService userProfileService;

		public CartController(ICartService cartService, IUserProfileService userProfileService, IAddressService addressService)
		{
			this.cartService = cartService;
			this.userProfileService = userProfileService;
			this.addressService = addressService;
		}

		[HttpGet]
		[Authorize]
        public async Task<IActionResult> Index()
        {
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			var model = await this.addressService.GetAddressAsync(userProfileGuid);

			if (model == null)
			{
				return View(model);
			}

			return View(model);
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> AllProductsInCart()
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			var prodcutsInCart = await this.cartService.GetProductsInCart(userProfileGuid);

			var response = new
			{
				products = prodcutsInCart,
			};

			return Json(response);
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> UpdateCart([FromBody] UpdateCartViewModel model)
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			Guid productGuid = Guid.NewGuid();

			if (!this.IsGuidValid(model.ProductId, ref productGuid))
			{
				return View();
			}

			int result = await this.cartService.UpdateCartProductCount(userProfileGuid, productGuid, model.Quantity);
			
			if(result == -1)
			{
				return View();
			}

			return Ok(result);
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> AddToCart([FromBody] string productId)
		{
			Guid productGuid = Guid.NewGuid();

			if (!this.IsGuidValid(productId, ref productGuid))
			{
				return View();
			}

			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			bool result = await this.cartService.AddProductToCart(userProfileGuid, productGuid);

			return Ok(result);
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> RemoveFromCart([FromBody] string productId)
		{
			Guid productGuid = Guid.NewGuid();

			if (!this.IsGuidValid(productId, ref productGuid))
			{
				return View();
			}

			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			bool result = await this.cartService.RemoveProductFromCart(userProfileGuid, productGuid);

			if (!result)
			{
				return View();
			}

			return Ok();
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> IsProductInCart([FromQuery] string productId)
		{
			Guid productGuid = Guid.NewGuid();

			if (!this.IsGuidValid(productId, ref productGuid))
			{
				return View();
			}

			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return Ok(false);
			}

			bool result = await this.cartService.IsProductInCart(userProfileGuid, productGuid);

			return Ok(result);
		}

    }
}

OnlineShop/Controllers/ProfileController.cs
namespace OnlineShop.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using Application.Extensions;
    using Application.Services.Interfaces;
    using Application.ViewModels.Profile;

    public class ProfileController : Controller
    {
        private readonly IUserProfileService userProfileService;

        public ProfileController(IUserProfileService userProfileService)
        {
            this.userProfileService = userProfileService;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index()
        {
            Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

            if (userProfileGuid == Guid.Empty)
            {
                return View();
            }

            UserProfileViewModel userProfile = await userProfileService.GetUserProfileById(userProfileGuid);

            return View(userProfile);
        }
	}
}

OnlineShop/Controllers/ShopController.cs
namespace OnlineShop.Web.Controllers
{
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Mvc;

	using Application.Services.Interfaces;
	using Application.ViewModels.Shop;

	using static Application.Extensions.ControllerExtensions;

	public class ShopController : Controller
    {
        private const int pageSize = 10; //Products displayed per page. 10 is default

		private readonly IProductService productService;
		private readonly IWishlistService wishlistService;
		private readonly ICartService cartService;
		private readonly IUserProfileService userProfileService;

		public ShopController(IProductService productService, IWishlistService wishlistService, ICartService cartService, IUserProfileService userProfileService)
        {
            this.productService = productService;
            this.wishlistService = wishlistService;
            this.cartService = cartService;
			this.userProfileService = userProfileService;
		}

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			return View();
        }

		[HttpPost]
		public async Task<IActionResult> AllProductsFiltered([FromBody] FilterOptionsViewModel filters)
		{
			int currentPage = filters.CurrentPage;
			int chunkIndex = (currentPage-1) * pageSize; 
			int chunkSize = pageSize;   

			int skip = chunkIndex * chunkSize;

			var filteredProducts = await this.productService.GetProductsChunkFilteredAsync(filters, chunkIndex, chunkSize);

			int totalFilteredProducts = await this.productService.GetAllFilteredProductCountAsync(filters);

			int totalPages = (int)Math.Ceiling((double)totalFilteredProducts / chunkSize);

			var response = new
			{
				products = filteredProducts,
				totalPages = totalPages,
				currentPage = currentPage
			};

			return Json(response);
		}

        [HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> AddNewProduct()
        {
			HttpContext.Session.SetString("PreviousPage", Request.Headers["Referer"].ToString());

			return View();
        }

        [HttpPost]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> AddNewProduct(AddNewProductViewModel model)
        {
			string previousPage = HttpContext.Session.GetString("PreviousPage");

			if (!ModelState.IsValid)
            {
                return View(model);
            }

			bool result = await this.productService.AddNewProductAsync(model);

            if (!result)
            {
                return View();
            }

			if (previousPage.Contains("CoreAdmin"))
			{
				return Redirect(previousPage);
			}
            else
            {
				return RedirectToAction(nameof(Index));
			}
            
        }

        [HttpGet]
		[Authorize(Roles = "Admin")]
		public async Task<IActionResult> EditProduct(string id)
        {
			HttpContext.Session.SetString("PreviousPage", Request.Headers["Referer"].ToString());

			Guid productGuid = Guid.Empty;
            bool isIdValid = this.IsGuidValid(id, ref productGuid);
            if (!isIdValid)
            {
                return RedirectToAction(nameof(Index));
            }

            EditProductViewModel formModel = await productService
                .GetEditProductByIdAsync(productGuid);

            return View(formModel);
        }

		[HttpPost]
		[Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditProduct(EditProductViewModel model)
        {
			string previousPage = HttpContext.Session.GetString("PreviousPage");

			if (!ModelState.IsValid)
            {
                return View(model);
            }

            bool result = await productService.EditProductAsync(model);

			if (!result)
			{
				return View();
			}

			if (previousPage.Contains("CoreAdmin"))
			{
				return Redirect(previousPage);
			}
			else
			{
				return RedirectToAction(nameof(Index));
			}
        }

		[HttpGet]
		[Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveProduct(string id)
        {
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			HttpContext.Session.SetString("PreviousPage", Request.Headers["Referer"].ToString());

			Guid productGuid = Guid.Empty;
            bool isIdValid = this.IsGuidValid(id, ref productGuid);
            if (!isIdValid)
            {
                return RedirectToAction(nameof(Index));
            }

            RemoveProductViewModel formModel = await productService
                .GetRemoveProductByIdAsync(productGuid);

			bool removingProductFromWishlists = await wishlistService
				.RemoveProductFromWishlist(userProfileGuid, productGuid);

			bool removingProductFromCarts = await cartService
				.RemoveProductFromCart(userProfileGuid, productGuid);

			return View(formModel);
        }

		[HttpPost]
		[Authorize(Roles = "Admin")]
        public async Task<IActionResult> RemoveProduct(string id, RemoveProductViewModel model)
        {
			string previousPage = HttpContext.Session.GetString("PreviousPage");

			Guid productGuid = Guid.Empty;
            bool isIdValid = this.IsGuidValid(id, ref productGuid);

            bool result = await productService.RemoveProductAsync(productGuid);

			if (!result)
			{
				return View();
			}

			if (previousPage.Contains("CoreAdmin"))
			{
				return Redirect(previousPage);
			}
			else
			{
				return RedirectToAction(nameof(Index));
			}
		}

        [HttpGet]
        public async Task<IActionResult> ProductDetails(string id)
        {
            Guid productGuid = Guid.Empty;
            bool isIdValid = this.IsGuidValid(id, ref productGuid);
            if (!isIdValid)
            {
                return RedirectToAction(nameof(Index));
            }

            ProductDetailsViewModel product = 
             await this.productService.GetProductDetailsAsync(productGuid);

            return View(product);
        }

	}
}

OnlineShop/Controllers/WishlistController.cs
namespace OnlineShop.Web.Controllers
{
	using Microsoft.AspNetCore.Authorization;
	using Microsoft.AspNetCore.Mvc;

	using Application.Services.Interfaces;

	using static Application.Extensions.ControllerExtensions;
	using System.Diagnostics;

	public class WishlistController : Controller
	{
		private readonly IWishlistService wishlistService;
		private readonly IUserProfileService userProfileService;

		public WishlistController(IWishlistService wishlistService, IUserProfileService userProfileService)
		{
			this.wishlistService = wishlistService;
			this.userProfileService = userProfileService;
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> Index()
		{
			return View();
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> AllProductsInWishlist()
		{
			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			var productsInWishlist = await this.wishlistService.GetProductsInWishlist(userProfileGuid);

			var response = new
			{
				products = productsInWishlist,
			};

			return Json(response);
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> AddToWishlist([FromBody] string productId)
		{
			Guid productGuid = Guid.NewGuid();

			if (!this.IsGuidValid(productId, ref productGuid))
			{
				return View();
			}

			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			bool result = await this.wishlistService.AddProductToWishlist(userProfileGuid, productGuid);

			if (!result)
			{
				return View();
			}

			return Ok();
		}

		[HttpPost]
		[Authorize]
		public async Task<IActionResult> RemoveFromWishlist([FromBody] string productId)
		{
			Guid productGuid = Guid.NewGuid();

			if (!this.IsGuidValid(productId, ref productGuid))
			{
				return View();
			}

			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return View();
			}

			bool result = await this.wishlistService.RemoveProductFromWishlist(userProfileGuid, productGuid);

			if (!result)
			{
				return View();
			}

			return Ok();
		}

		[HttpGet]
		[Authorize]
		public async Task<IActionResult> IsProductInWishlist([FromQuery] string productId)
		{
			Guid productGuid = Guid.NewGuid();

			if (!this.IsGuidValid(productId, ref productGuid))
			{
				return View();
			}

			Guid userProfileGuid = await this.GetUserProfileGuid(userProfileService);

			if (userProfileGuid == Guid.Empty)
			{
				return Ok(false);
			}

			bool result = await this.wishlistService.IsProductInWishlist(userProfileGuid, productGuid);

			return Ok(result);
		}
	}
}

OnlineShop/Views/Shared/ThankYou.cshtml
@section PageStyles {
    <link rel="stylesheet" href="~/css/ThankYou.css" asp-append-version="true" />
}

<header>
    <h1>Thank you for making a purchase!</h1>
    <h2>Thank you for choosing BikeOrbit!</h2>
    <svg class="smile-svg" width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
        <circle cx="50" cy="50" r="48" stroke="darkgray" stroke-width="2" fill="none"></circle>
        <circle cx="35" cy="40" r="5" fill="darkgray"></circle>
        <circle cx="65" cy="40" r="5" fill="darkgray"></circle>
        <path d="M35 60 Q50 80, 65 60" stroke="darkgray" stroke-width="2" fill="none"></path>
    </svg>
</header>

OnlineShop/Views/Shared/_FooterPartial.cshtml
<div class="footer">
    <small>© 2024 - Bike Orbit - All Rights Reserved.</small>
    <div class="social-links">
        <a href="#">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"></path>
            </svg>
        </a>
        <a href="#">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" version="1.1" viewBox="0 0 16 16" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <path d="M8 0.198c-4.418 0-8 3.582-8 8 0 3.535 2.292 6.533 5.471 7.591 0.4 0.074 0.547-0.174 0.547-0.385 0-0.191-0.008-0.821-0.011-1.489-2.226 0.484-2.695-0.944-2.695-0.944-0.364-0.925-0.888-1.171-0.888-1.171-0.726-0.497 0.055-0.486 0.055-0.486 0.803 0.056 1.226 0.824 1.226 0.824 0.714 1.223 1.872 0.869 2.328 0.665 0.072-0.517 0.279-0.87 0.508-1.070-1.777-0.202-3.645-0.888-3.645-3.954 0-0.873 0.313-1.587 0.824-2.147-0.083-0.202-0.357-1.015 0.077-2.117 0 0 0.672-0.215 2.201 0.82 0.638-0.177 1.322-0.266 2.002-0.269 0.68 0.003 1.365 0.092 2.004 0.269 1.527-1.035 2.198-0.82 2.198-0.82 0.435 1.102 0.162 1.916 0.079 2.117 0.513 0.56 0.823 1.274 0.823 2.147 0 3.073-1.872 3.749-3.653 3.947 0.287 0.248 0.543 0.735 0.543 1.481 0 1.070-0.009 1.932-0.009 2.195 0 0.213 0.144 0.462 0.55 0.384 3.177-1.059 5.466-4.057 5.466-7.59 0-4.418-3.582-8-8-8z"></path>
            </svg>
        </a>
        <a href="#">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" role="img" viewBox="0 0 24 24" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"></path>
            </svg>
        </a>
    </div>
</div>

OnlineShop/Views/Shared/_HeaderPartial.cshtml
<nav>
    <div class="nav-logo-home-button">
        <a asp-controller="Home" asp-action="Index">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" role="img" viewBox="0 0 24 24" height="1.2em" width="1.2em" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 2 C17.5 2, 22 7.5, 22 12 C22 16.5, 17.5 22, 12 22 C6.5 22, 2 16.5, 2 12 C2 7.5, 6.5 2, 12 2 M12 7 L8 11 L12 11 L12 17 L16 14 L12 14 L12 7" fill="none" stroke="currentColor" stroke-width="3" />
            </svg>
            <span class="brand-name">BikeOrbit</span>
        </a>
    </div>
    <div class="nav-input-search">
        <input id="searchInput" name="input" placeholder="Search" spellcheck="false" />
        <a id="searchLink" href="#" onclick="updateSearchLink()">
            <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 24 24" height="13px" width="13px" xmlns="http://www.w3.org/2000/svg">
                    <path fill="none" stroke="#000" stroke-width="2" d="M15,15 L22,22 L15,15 Z M9.5,17 C13.6421356,17 17,13.6421356 17,9.5 C17,5.35786438 13.6421356,2 9.5,2 C5.35786438,2 2,5.35786438 2,9.5 C2,13.6421356 5.35786438,17 9.5,17 Z"></path>
                </svg>
            </a>
    </div>
    <div class="nav-link-container">
        @if (User.IsInRole("Admin"))
        {
            <a href="@Url.Action("Index", "CoreAdmin")">Manage</a>
        }
        @if (@User!.Identity!.IsAuthenticated)
        {
            <a asp-controller="Profile" asp-action="Index" id="profile-link">Profile</a>
        } 
        else
        {
            <a asp-area="Identity" asp-page="/Account/Login">Login</a>
        }
        <a asp-controller="Shop" asp-action="Index" id="shop-link">Shop</a>
        <a asp-controller="Wishlist" asp-action="Index" id="wishlist-link">
            <span class="cart-text">Wishlist</span>
            <svg stroke="currentColor" fill="none" stroke-width="0" viewBox="0 0 24 24" class="wishlist" height="25" width="25" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M12.0122 5.57169L10.9252 4.48469C8.77734 2.33681 5.29493 2.33681 3.14705 4.48469C0.999162 6.63258 0.999162 10.115 3.14705 12.2629L11.9859 21.1017L11.9877 21.0999L12.014 21.1262L20.8528 12.2874C23.0007 10.1395 23.0007 6.65711 20.8528 4.50923C18.705 2.36134 15.2226 2.36134 13.0747 4.50923L12.0122 5.57169ZM11.9877 18.2715L16.9239 13.3352L18.3747 11.9342L18.3762 11.9356L19.4386 10.8732C20.8055 9.50635 20.8055 7.29028 19.4386 5.92344C18.0718 4.55661 15.8557 4.55661 14.4889 5.92344L12.0133 8.39904L12.006 8.3918L12.005 8.39287L9.51101 5.89891C8.14417 4.53207 5.92809 4.53207 4.56126 5.89891C3.19442 7.26574 3.19442 9.48182 4.56126 10.8487L7.10068 13.3881L7.10248 13.3863L11.9877 18.2715Z" fill="currentColor"></path>
            </svg>
            <span class="wishlist-count" style="display:none;"></span>
        </a>
        <a asp-controller="Cart" asp-action="Index" id="cart-link">
            <span class="cart-text">Cart</span>
            <svg stroke="currentColor" fill="none" stroke-width="0" viewBox="0 0 24 24" class="cart" height="25" width="25" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M5.79166 2H1V4H4.2184L6.9872 16.6776H7V17H20V16.7519L22.1932 7.09095L22.5308 6H6.6552L6.08485 3.38852L5.79166 2ZM19.9869 8H7.092L8.62081 15H18.3978L19.9869 8Z" fill="currentColor"></path>
                <path d="M10 22C11.1046 22 12 21.1046 12 20C12 18.8954 11.1046 18 10 18C8.89543 18 8 18.8954 8 20C8 21.1046 8.89543 22 10 22Z" fill="currentColor"></path>
                <path d="M19 20C19 21.1046 18.1046 22 17 22C15.8954 22 15 21.1046 15 20C15 18.8954 15.8954 18 17 18C18.1046 18 19 18.8954 19 20Z" fill="currentColor"></path>
            </svg>
            <span class="cart-count" style="display:none;"></span>
        </a>
    </div>
    <div class="hamburger-icon">
        <svg stroke="currentColor" fill="none" stroke-width="0" viewBox="0 0 15 15" height="20" width="20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M1.5 3C1.22386 3 1 3.22386 1 3.5C1 3.77614 1.22386 4 1.5 4H13.5C13.7761 4 14 3.77614 14 3.5C14 3.22386 13.7761 3 13.5 3H1.5ZM1 7.5C1 7.22386 1.22386 7 1.5 7H13.5C13.7761 7 14 7.22386 14 7.5C14 7.77614 13.7761 8 13.5 8H1.5C1.22386 8 1 7.77614 1 7.5ZM1 11.5C1 11.2239 1.22386 11 1.5 11H13.5C13.7761 11 14 11.2239 14 11.5C14 11.7761 13.7761 12 13.5 12H1.5C1.22386 12 1 11.7761 1 11.5Z" fill="currentColor"></path>
        </svg>
    </div>
    <div class="cross-tab-icon cross-tab-icon-mobile" style="display: none;">
        <svg stroke="currentColor" fill="none" stroke-width="0" viewBox="0 0 15 15" color="rgb(106, 106, 65)" height="25" width="25" xmlns="http://www.w3.org/2000/svg" style="color: rgb(106, 106, 65);">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M11.7816 4.03157C12.0062 3.80702 12.0062 3.44295 11.7816 3.2184C11.5571 2.99385 11.193 2.99385 10.9685 3.2184L7.50005 6.68682L4.03164 3.2184C3.80708 2.99385 3.44301 2.99385 3.21846 3.2184C2.99391 3.44295 2.99391 3.80702 3.21846 4.03157L6.68688 7.49999L3.21846 10.9684C2.99391 11.193 2.99391 11.557 3.21846 11.7816C3.44301 12.0061 3.80708 12.0061 4.03164 11.7816L7.50005 8.31316L10.9685 11.7816C11.193 12.0061 11.5571 12.0061 11.7816 11.7816C12.0062 11.557 12.0062 11.193 11.7816 10.9684L8.31322 7.49999L11.7816 4.03157Z" fill="currentColor">
            </path>
        </svg>
    </div>

</nav> 

OnlineShop/Views/Shared/_Layout.cshtml
@{
	var hideLayoutParts = ViewData["HideLayoutParts"] as bool? ?? false;
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"]</title>

	<link rel="stylesheet" href="~/css/App.css" asp-append-version="true" />

	@if (!hideLayoutParts)
	{
		<link rel="stylesheet" href="~/css/Header.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/css/Footer.css" asp-append-version="true" /> 
	}

	@await RenderSectionAsync("PageStyles", required: false)

	<script>
		var isUserAuthenticated = '@User.Identity.IsAuthenticated'.toLowerCase() === 'true';

		var baseUrl = '@ViewData["BaseUrl"]';
	</script>
</head>
<body>
	<div id="root">
		<div class="App">

			@if (!hideLayoutParts)
			{
				@await Html.PartialAsync("_HeaderPartial.cshtml");
				<script src="~/js/HeaderAnimations.js" asp-append-version="true"></script>
				<script src="~/js/Header.js" asp-append-version="true"></script>
			}

			@RenderBody()

			@if (!hideLayoutParts)
			{
				@await Html.PartialAsync("_FooterPartial.cshtml");
			}

			@await RenderSectionAsync("PageScripts", required: false)
			@await RenderSectionAsync("Scripts", required: false) @* Default scripts *@
		</div>
	</div>
</body>
</html>